# Generated by Django 5.2.4 on 2025-07-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0003_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
